---
  - name: Copying prometheus.yml to /opt/prometheus
    template:
      src: "{{role_path}}/templates/prometheus.yml.j2"
      dest: "{{prometheus_dir}}/prometheus.yml"
      owner: prometheus
      group: prometheus
      mode: '0755'
    become: true
    notify: Restart Prometheus